### ISSUE TITLE
Damage Reservation creation

### ISSUE THREAD

**Issue by xliu3** [umts/probable-engine#156] opened 2016-09-06 14:17 UTC
## APP part
- need to assign a specific item/cart to API
- need to re-assign new item/cart to the customer if the damaged item/cart was rented during the repair time period
- need to cancel the rental reservation if there is no other available item to be replace
- need to send a notice if the rental reservation is cancel

---
## API part
- create damage reservation creation logic

**Comment by anmerkl** [comment] 2016-09-09 20:47
@owlee Dibs.

**Comment by tomecho** [comment] 2016-10-07 17:10
duplicate of #111

**Closed** 2016-12-08 19:26 UTC
